model:
  model_path: model/Qwen3-0.6B
  tokenizer_path: model/qwen3_sparktts_with_under_special
  attn_implementation: flash_attention_2

data:
  # Stage3 combine highqual MOS built from the refreshed parquet_new dataset.
  train_path: data/stage3/parquet
  data_type: conversation
  chat_template: chatml
  datasets_type: mapping
  max_seq_len: 3072
  train_size: 3200000000
  audio_his_drop_prob: 0.0
  audio_his_drop_ratio_max: 0.10
  audio_his_drop_skip_prefix_tokens: 32
  text_keys: messages
  num_workers: 16
  prefetch_factor: 4
  drop_last: true
  pin_memory: true

train:
  output_dir: outputs/stage3_0p6b
  data_parallel_mode: ddp
  ulysses_parallel_size: 1
  global_batch_size: 96
  micro_batch_size: 4
  num_train_epochs: 1

  rmpad: false
  rmpad_with_pos_ids: true
  bsz_warmup_ratio: 0.007
  dyn_bsz: true
  dyn_bsz_margin: 0
  dyn_bsz_buffer_size: 200

  optimizer: adamw
  lr: 3.0e-6
  lr_min: 3.0e-7
  lr_warmup_ratio: 0.08
  lr_decay_style: cosine
  weight_decay: 0.1
  max_grad_norm: 1.0

  enable_mixed_precision: true
  enable_gradient_checkpointing: false
  enable_full_shard: true
  enable_fsdp_offload: false
  enable_activation_offload: false
  init_device: cuda
  enable_full_determinism: false
  empty_cache_steps: 500

  ckpt_manager: dcp
  load_checkpoint_path: ""
  load_model_only: true
  save_steps: 0
  logging_steps: 10
  save_epochs: 0
  save_epoch_points:
    - 0.5
    - 0.75
    - 1.0
    - 1.25
    - 1.5
    - 1.75
    - 2.0
  save_hf_weights: false
  keep_last_checkpoints: 0
  keep_best_and_last_checkpoints: false

  wandb_project: VeOmni
  wandb_name: qwen3-satge3-combine-highqual-mos-parquet-new-6gpu-2ep
